version: 2
jobs:
  test:
    working_directory: ~/likecoin-store
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm uninstall npm -g && yarn global add npm@6
      - restore_cache:
          key: likecoin-store-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm ci
      - run:
          name: Lint Test
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Server Test
          command: npm start
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://127.0.0.1:3000/
      - save_cache:
          key: likecoin-store-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - "$HOME/.npm"
  unit_test:
    working_directory: ~/likecoin-store
    docker:
      - image: selenium/standalone-chrome:3.11.0
        user: root
    steps:
      - checkout
      - restore_cache:
          key: likecoin-store-unit-test-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Node Environment
          command: |
            sudo apt-get update
            sudo apt-get -y install curl git make g++ net-tools
            sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get -y install nodejs
            sudo npm install npm@6 -g
      - run:
          name: Dependencies
          command: npm ci
      - run:
          name: Unit Test Server
          command: node test/runner.js
          background: true
      - run:
          name: Curl Unit Test Server
          command: |
            sleep 5
            wget -O- --retry-connrefused --waitretry=5 -t 10 http://localhost:3000/ > /dev/null
      - run:
          name: Unit Test (Nightwatch)
          command: xvfb-run --server-args="-screen 0 1600x1200x24" npm run test:e2e
      - run:
          name: Unit Test (Backend)
          command: npm run test:api
      - save_cache:
          key: likecoin-store-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - "$HOME/.npm"
  deploy_rinkeby:
    working_directory: ~/likecoin-store
    docker:
      - image: lakoo/node-gcloud-docker
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - TERM: dumb
      - GOOGLE_APPLICATION_CREDENTIALS: /tmp/account-auth.json
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > /account-auth.json
            gcloud auth activate-service-account --key-file /account-auth.json
            gcloud config set project ${PROJECT_NAME}
            gcloud --quiet config set container/cluster ${POC_CLUSTER_NAME}
            gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${POC_CLUSTER_NAME}
      - setup_docker_engine
      - run:
          name: Build image
          command: |
            gcloud docker -- pull us.gcr.io/${PROJECT_NAME}/like-store:latest || true
            docker build . -t like-store --cache-from us.gcr.io/${PROJECT_NAME}/like-store:latest --build-arg IS_TESTNET='TRUE' --build-arg INTERCOM_APPID=${TEST_INTERCOM_APPID} --build-arg STRIPE_TOKEN=${STRIPE_TEST_TOKEN}
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:latest
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:test-${CIRCLE_SHA1}
      - run:
          name: Push images
          command: |
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:latest
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:test-${CIRCLE_SHA1}
      - deploy:
          name: Deploy
          command: |
            kubectl patch deployment like-store-rinkeby -p '{"spec":{"template":{"spec":{"containers":[{"name":"like-store","image":"us.gcr.io/'"$PROJECT_NAME"'/like-store:test-'"$CIRCLE_SHA1"'"}]}}}}'
  deploy_mainnet:
    working_directory: ~/likecoin-store
    docker:
      - image: lakoo/node-gcloud-docker
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - TERM: dumb
      - GOOGLE_APPLICATION_CREDENTIALS: /tmp/account-auth.json
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > /account-auth.json
            gcloud auth activate-service-account --key-file /account-auth.json
            gcloud config set project ${PROJECT_NAME}
            gcloud --quiet config set container/cluster ${POC_CLUSTER_NAME}
            gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${POC_CLUSTER_NAME}
      - setup_docker_engine
      - run:
          name: Build image
          command: |
            gcloud docker -- pull us.gcr.io/${PROJECT_NAME}/like-store:latest || true
            docker build . -t like-store --cache-from us.gcr.io/${PROJECT_NAME}/like-store:latest --build-arg INTERCOM_APPID=${INTERCOM_APPID} --build-arg GA_TRACKING_ID=${GA_TRACKING_ID} --build-arg GTM_ID=${GTM_ID} --build-arg STRIPE_TOKEN=${STRIPE_PROD_TOKEN}
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:latest
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:main-${CIRCLE_SHA1}
      - run:
          name: Push images
          command: |
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:latest
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:main-${CIRCLE_SHA1}
      - deploy:
          name: Deploy
          command: |
            kubectl patch deployment like-store-main -p '{"spec":{"template":{"spec":{"containers":[{"name":"like-store","image":"us.gcr.io/'"$PROJECT_NAME"'/like-store:main-'"$CIRCLE_SHA1"'"}]}}}}'

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - unit_test
      - hold_deploy_rinkeby:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
                - /feature.*/
          requires:
           - test
      - hold_deploy_mainnet:
          type: approval
          filters:
            branches:
              only: master
          requires:
           - test
      - deploy_rinkeby:
          requires:
            - hold_deploy_rinkeby
      - deploy_mainnet:
          requires:
            - hold_deploy_mainnet
